### ISSUE TITLE
defaultOptions aren't honored

### ISSUE THREAD

**Issue by obambrough** [augustocdias/vscode-shell-command#107]
Actual behavior:

The command doesn't return anything and an exception is thrown "The command for input 'selectRepository' returned empty result."

Expected behavior:

The list of values from the input's defaultOptions will be listed to choose from.

Looking at the code I see on line 240 of CommandHandler.ts the quickPick method will apply the defaultOptions if the input array has a length of 0 but I don't think that's ever triggered as the parseResult method on line 209 of CommandHandler.ts will throw an exception if there aren't any results.

**Comment by MarcelRobitaille** [comment]
This was likely broken in #96.

**Comment by MarcelRobitaille** [comment]
Thanks for the report. Fixed in 1.12.1. It's on my todo list to add tests to this stuff.
