### ISSUE TITLE
Environment variables are not sourced from vscode

### ISSUE THREAD

**Issue by hansaya** [augustocdias/vscode-shell-command#11]
Any environment variables set within settings.json does not get picked up when executing a command. I could set the environment within the args{} but you cannot read what environment variable already set so you ended up overriding the existing variable. This makes it harder to set something like "PATH".

Example I want to be able to do
```
        "args":{
            "command": "echo $env:PATH;",
            "env": {
                "PATH": "${env:PATH};C:\\Program Files\\Git\\bin;",
            }
         }
```
Or just simply source all the env variables from vscode settings.

As a workaround I was able to set the PATH before the execution of vscode but this is a extra step developer has to run before opening up the workspace.

Thanks for creating this extension and let me how could I help to get this fixed.

**Comment by augustocdias** [comment]
Thanks for the issue... It seems env vars can be obtained from the `getConfiguration` function from the workspace.
https://code.visualstudio.com/api/references/vscode-api#workspace

**Comment by koniroman** [comment]
It shall be solved by https://github.com/augustocdias/vscode-shell-command/pull/19#issue-572450264 .
