### ISSUE TITLE
this.getDefault(...).join is not a function

### ISSUE THREAD

**Issue by johansegers** [augustocdias/vscode-shell-command#110]
We get following error:
this.getDefault(...).join is not a function

used config:
```json
        {
            "id": "user",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "grep '^db\\.[A-Za-z]*\\.username' 'dev.properties' | grep -Ewv \"db.ut*|db.logger*|db.apex*|db.ava*|db.datapump*|db.prj*\" | awk -F \"db.|.username\" \"{print $2}\"",
                "cwd": "${workspaceFolder}/conf/env/",
                "description": "db user",
                "taskId": "user",
                "rememberPrevious": true
            }
        }
```

**Comment by MarcelRobitaille** [comment]
@johansegers which version are you using?

**Comment by johansegers** [comment]
![image](https://github.com/user-attachments/assets/eb60ad0b-fa7e-4436-98d4-a8fcad7a685a)

**Comment by MarcelRobitaille** [comment]
I meant which version of the extension. But it's OK, I think I found the problem.

**Comment by johansegers** [comment]
1.12.1

**Comment by MarcelRobitaille** [comment]
Thanks.

The problem is that I changed the default state to an array since we now support multiselect. However, this change is backwards incompatible with older installations of the extension where the value is still saved inside of vscode as a string.

**Comment by MarcelRobitaille** [comment]
Please check version 1.12.2
