### ISSUE TITLE
Option to useSingleResult when only one result returned

### ISSUE THREAD

**Issue by lucono** [augustocdias/vscode-shell-command#13]
Just like the very useful `useFirstResult` option, it would be great to have a `useSingleResult` option which skips the Quick Pick dialog when there is only one result returned from the command.

**Comment by lucasintegral** [comment]
I've submitted PR #14 to contribute this feature, and happy to make any additional modifications you want to the code. This extension has been of tremendous use to me, thank you for it.

**Comment by lucono** [comment]
I've submitted PR #14 to contribute this feature, and happy to make any additional modifications you want to the code. This extension has been of tremendous use to me, thank you for it.

**Comment by augustocdias** [comment]
Thank you very much for the PR. 
I'll release it soon to the marketplace :)

**Comment by lucono** [comment]
Thanks @augustocdias
