### ISSUE TITLE
Unable to run some commands, and VScode freezes after it.

### ISSUE THREAD

**Issue by Haiderahandali** [augustocdias/vscode-shell-command#15]
I am trying to run the following command on bash, macOS

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "runAllCpp",
            "type": "shell",
            "command": "g++-10",
            "args": ["''${input:DEBUG_URI}''"],
            "problemMatcher": []
        }
    ],

    "inputs": [
        {
            "id": "DEBUG_URI",
            "type": "command",
            "command": "shellCommand.execute",
                "args": {
                "command": "find . -name '*.cpp'" ,
                "useFirstResult": "true",
            }
        }
    ],
}
```

other commands such as echo are fine.

**Comment by augustocdias** [comment]
How many results does this command returns in your folder? 


I suspect it might be because there's too many entries and I haven't implemented limiting.

**Comment by Haiderahandali** [comment]
Considering I am running it with `find .` which refers to my current folder,
it should just return 3 CPP files,
as mentioned, I tried multiple shell commands and they worked, this one, isn't
I am suspecting it has something to do with the single quotes I am using to specify only CPP files.
Have you managed to get it to run?

**Comment by augustocdias** [comment]
The problem is that the extension is not using the current folder as the working folder for the shell command. It is using `/`. You can inform the `cwd` option to solve this issue. I'll set the current folder as default
