### ISSUE TITLE
Option to add default value?

### ISSUE THREAD

**Issue by josephaVMW** [augustocdias/vscode-shell-command#17]
Hey there! Really useful extension, thank you for this.

I was wondering if there is any way to specify a default value for the input list, as there is with `"default"` when using an input with `"type": "promptString"`.

Thanks!

**Comment by augustocdias** [comment]
Yes. It should be possible.

Aside from adding the option, this would require to change the `handle` and the `parseResult` methods in [this file](https://github.com/augustocdias/vscode-shell-command/blob/master/src/lib/CommandHandler.ts).

**Comment by fifofonix** [comment]
Very useful.  Not sure whether this is the same thing exactly but when a command returns a single value it would be nice if there was a no prompt option which dispenses with the quick pick.  Sometimes the value selected may be a temporary token and it would be good for it not to be shown on the screen even for the short carriage return.

**Comment by augustocdias** [comment]
@fifofonix this is already supported.

Please check the doc:
* `useFirstResult`: skip 'Quick Pick' dialog and use first result returned from the command
* `useSingleResult`: skip 'Quick Pick' dialog and use the single result if only one returned from the command

**Comment by fifofonix** [comment]
@augustocdias thanks so much for this very useful extension.  Apologies for missing it in the docs.
