### ISSUE TITLE
Skip pick option dialog

### ISSUE THREAD

**Issue by lgmys** [augustocdias/vscode-shell-command#2]
Hello everybody,

Currently, whenever the command is executed, I am presented with a selection dialog. I would like to have an option allowing me to skip it and go with first value returned from the command automatically.

Edit: Added a [PR](https://github.com/augustocdias/vscode-shell-command/pull/3) supporting the thing I have in mind.

**Comment by augustocdias** [comment]
I like the formatting. What have you used to do it (default vscode settings?)

**Comment by lgmys** [comment]
Prettier I think, I have some defaults set up. I did not mean to alter what you had initially, sorry. I can resubmit the PR if it is an issue.

W dniu wt., lip 23, 2019 o 11:47, Augusto César Dias <notifications@github.com> napisał(a):

**Comment by augustocdias** [comment]
It's okay. 
Don't worry.
I'll check it out :)

**Comment by augustocdias** [comment]
I have published already the change. Could you share your prettier settings? :)

**Comment by lgmys** [comment]
https://gist.github.com/lgmys/dbb66f6d209c151d07106cb750a7bb61
