### ISSUE TITLE
The ${fileDirname} variable is empty on launch.json

### ISSUE THREAD

**Issue by sdsnatcher** [augustocdias/vscode-shell-command#22]
I'm trying to use the ${fileDirname} variable on a script inside the launch.json, but it's not working at all. I tried it using the two approached bellow,  but none of them worked:

1) Path to the file
```
    "inputs": [
        {
            "id": "SERVER",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "type ${fileDirname}\\Tests\\server.txt",
                "useFirstResult": "true",
            }
        },

```

2) Cwd to dir
```
    "inputs": [
        {
            "id": "SERVER",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "type Tests\\server.txt",
                "cwd": "${fileDirname}"
                "useFirstResult": "true",
            }
        },

```

The value of the ${fileDirname} seems to always be empty.

OTOH, if I change it to the ${workspaceFolder} variable, it works fine but that's not the folder I need.

Tested with VSCode v1.56.2 on Windows 2016 build 1607.

**Comment by augustocdias** [comment]
Do you have any active editor? This variable resolves to the current open file in the editor. If none or if the editor is not focused it will be indeed empty. 

Mind I ask what are you trying to do?

**Comment by sdsnatcher** [comment]
Yes, I have a source file open in the VSCode editor. The ${file} variable is being set accordingly, but the ${fileDirname} isn't.

For now, I have implemented the following convoluted workaround and it's working fine, but ideally ${fileDirname} should work correctly:


```
  "inputs": [
        {
            "id": "SERVER",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "bash -c \"cat $(dirname $FILENAME)/Tests/server.txt\"",
                "useFirstResult": "true",
                "env": {
                    "FILENAME": "${file}"
                }
            }
        }]

```

> Mind I ask what are you trying to do?

The code inside the "command" tag here is merely an example, similar to the ones you provided on the project README.md . Unfortunately, the real command can't be placed here.

But I can say that, on the real problem, I have to feed the executable being launched with some parameters it needs in the command line. There are many different command line tools to debug, and their parameters will be provided according to a standardized configuration file inside the respective Tests folder.

Each command line tool we have to debug has its own source code folder, and a respective Test folder inside that with the necessary parameter configuration.

**Comment by augustocdias** [comment]
I've just noticed you have a typo in your config. It is `fileDirName`, not `fileDirname`.
Can you check if this is the reason?

**Comment by detthiu** [comment]
I have encounter the same issue. I rewrote `fileDirname` to `fileDirName `and it worked.

**Comment by detthiu** [comment]
[https://code.visualstudio.com/docs/editor/variables-reference](https://code.visualstudio.com/docs/editor/variables-reference)
In the vscode variable, it is defined as `fileDirname`. `fileDirname` and `fileDirName` are mixed in tasks.json.

**Comment by sdsnatcher** [comment]
> https://code.visualstudio.com/docs/editor/variables-reference
> In the vscode variable, it is defined as `fileDirname`. `fileDirname` and `fileDirName` are mixed in tasks.json.

Yes, it seems that this was the source of the confusion. I used the same name as the vscode variables reference.

**Comment by sdsnatcher** [comment]
Anyway, isn't it better to change it to fileDirname, since this is the name in the [vscode variables reference](https://code.visualstudio.com/docs/editor/variables-reference) and avoid the potencial confusion?

**Comment by augustocdias** [comment]
Instead of changing and breaking other peoples setups, I'd make it case insensitive.

**Comment by sdsnatcher** [comment]
Ok, works for me.    :)

Another option could be to provide two variables, one with each name case variation.

**Comment by vindicatorr** [comment]
Is this applicable with `env:` set via:
```
    "options": {
      "env": {
        "TRYA": "A",
        "TRYB": "B",
        "TRYC": "C"
      }
    },
```
because I'm not getting any of that.
For a sanity check, I did succeed using `config:`.

Also
```
          "command": "/usr/bin/echo $test",
          "env": {
            "test": "${env:PATH}"
          },
```
succeeds while
```
          "command": "/usr/bin/echo $test",
          "env": {
            "test": "${env:TRYA}"
          },
```
fails
