### ISSUE TITLE
Running the contributed command 'shellCommand.execute' failed

### ISSUE THREAD

**Issue by rafalszuta** [augustocdias/vscode-shell-command#32]
When I use the example of this extension I always have a problem:
"Running the contributed command 'shellCommand.execute' failed"

**Comment by augustocdias** [comment]
At the moment it is not possible.  It was implemented to use the default from vscode settings but we had to revert because of #9 

since I don’t have a windows machine I can’t test and fix it.

**Comment by Penguinang** [comment]
@rafalszuta I think maybe you can specify powershell in "command" variable, like
```
"command": "powershell -Command \"echo 1\";"
```
