### ISSUE TITLE
Feature request: Allow new values

### ISSUE THREAD

**Issue by dslijepcevic** [augustocdias/vscode-shell-command#33]
Now that we have basic variable dependency resolution implemented in the extension itself, I think it would be really nice to support an equivalent of the `promptString` variable type. That way we would be able to create arbitrary multi-step inputs. It could be a mode where we display just the regular prompt, or, say, with `allowFreeInput: true` or `allowNewValues: true` the list could behave like autosugest. There is a [trick](https://github.com/microsoft/vscode/issues/89601#issuecomment-580133277) how to do it at the moment with QuickPick.

What do you think? If there is an interest and it can be merged _quickly_ (because we might need it in production soon), I apply to implement it, as well as maybe the default values feature.

Thanks,
Dusan

**Comment by augustocdias** [comment]
As long as you don’t break anything existing, you can go ahead and implement it. If everything is okay I can merge it quickly

**Comment by Abrahamsen3** [comment]
I'm looking for an implementation doing exactly what @dslijepcevic describes. Would this be hard to implement?
