### ISSUE TITLE
remember the value you previously entered and default to it the next time they are used

### ISSUE THREAD

**Issue by grzn** [augustocdias/vscode-shell-command#35]
should be useful to remember that last chosen value and use it as the default for the next time.

similar to https://marketplace.visualstudio.com/items?itemName=spadin.memento-inputs

**Comment by AngelEzquerra** [comment]
This would be awesome. It would also be nice to be able to specify a default value.

**Comment by quentingllmt** [comment]
Would be awesome, do you need help ?

**Comment by quentingllmt** [comment]
Ok i didn't wait. I have created a pull request for that feature #57 .

Would be nice if you guys can test.

**Comment by augustocdias** [comment]
Closed by #57
