### ISSUE TITLE
Make the ${fileBasenameNoExtension} variable available

### ISSUE THREAD

**Issue by sdsnatcher** [augustocdias/vscode-shell-command#36]
The ${fileBasenameNoExtension} is very useful for scripts, so please make it available.

Otherwise some juggling is always necessary to strip the extension from the filename provided by ${file}, instead of a simple/straightforward command line that could have been used if ${fileBasenameNoExtension} was available

On Windows this is particularly important, because there are much less command line tools to do that kind of text juggling for you.

**Comment by augustocdias** [comment]
Hi. Can you test this please? I added the suggested variable but I have no windows machine to test it.
