### ISSUE TITLE
"Dependent Input Variables Usage example" not working

### ISSUE THREAD

**Issue by blaylockbk** [augustocdias/vscode-shell-command#42]
Thanks for publishing this useful extension.
I just wanted to let you know that the "Dependent Input Variables Usage example" did not work in VS Code Version 1.68.1.

When I ran the example, the first input successfully listed the folders in the current folder, but the second input dialogue did not get any information about the `rootDir` I selected. Instead, it listed the contents of the `rootDir` again.

**Comment by augustocdias** [comment]
Can you post the configuration you used please?

**Comment by blaylockbk** [comment]
I apologize. This was a user error issue. After working through it again, I figured out my problem. The example works just fine.

I was trying to extend the example to list files in my home directory (outside the current workspace), and in order to list the nested folders, I needed to include the parent's path in all the commands. I'll put this here in case anyone else runs into this too. Thanks again for this handy extension!

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Nested input",
            "command": "ls /path/to/home/${input:rootDir}/${input:childDir}",
            "type": "shell",
            "problemMatcher": []
        }
    ],
    "inputs": [
        {
            "id": "rootDir",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "ls /path/to/home"
            }
        },
        {
            "id": "childDir",
            "type": "command",
            "command": "shellCommand.execute",
            "args": {
                "command": "ls /path/to/home/${input:rootDir}"
            }
        }
    ]
}

```
