### ISSUE TITLE
Failing to concatenate inputs for one task

### ISSUE THREAD

**Issue by uricata9** [augustocdias/vscode-shell-command#44]
Hi Team,
It seems that after your recent changes this feature it's broken.
So given the example with single root workspace

            {
                "command": "shellCommand.execute",
                "type": "command",
                "args": {
                    "command": "${workspaceFolder}/.devcontainer/setup.py --list_families",
                    "description": "Select the family",
                    "fieldSeparator": "|"
                },
                "id": "listFamilies"
            },
            {
                "command": "shellCommand.execute",
                "type": "command",
                "args": {
                    "command": "${workspaceFolder}/.devcontainer/setup.py --list_os --family ${input:listFamilies}",
                    "description": "Select the os",
                    "fieldSeparator": "|"
                },
                "id": "listOs"
            },

The resulting error is something like this:

![image](https://user-images.githubusercontent.com/15819563/180328130-f2c810d0-07b9-4b04-9d67-203bd691d2e0.png)

As you can see the command setup.py is called with listFamilies input but the value is missing after being selected 
to be used for the next input prompt

So, I don't know if the base case (single root workspace) is failing due this new variable introduced in your commit 7ea7dbee3dcf9e5652579b00fc06a65b9eb94523: folder.uri

Thank you for your work! It is a very useful extension!

Regs

**Comment by augustocdias** [comment]
Do you have a folder open in VSCode? Because all that changed is this. A workspace is always created when you open a folder.

**Comment by augustocdias** [comment]
If not, can you provide a script that returns any arbitrary data in this format you're testing so I can try it myself?

**Comment by uricata9** [comment]
> Do you have a folder open in VSCode? Because all that changed is this. A workspace is always created when you open a folder.

I'm not opening a folder, we work using open workspace feature. So, perhaps the problem is there. All inputs and tasks are defined inside de code-workspace

**Comment by augustocdias** [comment]
So the tasks is not in the config but rather in the root of the workspace? Can you share the structure so I can take a look and try to reproduce and fix it?

**Comment by uricata9** [comment]
> So the tasks is not in a folder but rather in the root of the workspace? Can you share the structure so I can take a look and try to reproduce and fix it?

I just created a repo that to reproduce the issue:https://github.com/uricata9/test-vscode

Steps to reproduce the issue:

1-> Open Workspace -> test.code-workspace
2 -> Remote-Containers -> Open workspace in Container
3 -> Run Task -> Setup Family

**Comment by uricata9** [comment]
> > So the tasks is not in a folder but rather in the root of the workspace? Can you share the structure so I can take a look and try to reproduce and fix it?
> 
> I just created a repo to reproduce the issue:https://github.com/uricata9/test-vscode
> 
> Steps to reproduce the issue:
> 
> 1-> Open Workspace -> test.code-workspace 2 -> Remote-Containers -> Open workspace in Container 3 -> Run Task -> Setup Family

It seems to be happening when you have tasks and launch in the code-workspace and in the .vscode folder in the root repo
(without .vscode in the root repo seems to work)
![image](https://user-images.githubusercontent.com/15819563/180495722-bae3f62c-38e0-4274-b939-cccf1e949933.png)

**Comment by augustocdias** [comment]
Can you check if latest commit fixed the issue?

**Comment by uricata9** [comment]
Thank you for your work here but it is still failing...

![image](https://user-images.githubusercontent.com/15819563/180725823-c403f0b2-dbf8-4e2b-bd50-6bb625f6c0ba.png)

**Comment by augustocdias** [comment]
I believe it has to do with container development... I tried your project but I was getting too many errors (I believe it is quite tied to your local environment).

**Comment by uricata9** [comment]
> I believe it has to do with container development... I tried your project but I was getting too many errors (I believe it is quite tied to your local environment).

Yeah sorry, I didn't delete all environment dependencies. Now, you should be able to reproduce de environment
Thanks!

**Comment by augustocdias** [comment]
It is working fine for me... I can't reproduce it

**Comment by uricata9** [comment]
I just added .vscode directory in the repo. It fails for me all the time... And only works with 1.7.0 version
Please, can you try again with this new .vscode directory in my repo? Thanks!

**Comment by augustocdias** [comment]
I could reproduce now. A fix should be live in a couple minutes.
