### ISSUE TITLE
Contribution-related questions

### ISSUE THREAD

**Issue by butteredptarmigan** [augustocdias/vscode-shell-command#6]
I have forked this repository in order to make a pull request introducing some minor change, which would take into account the user's preferred shell instead of just picking up default system shell.

Unfortunately, I found it quite uncomfortable to work with the code, as it had gotten a little spaghetti along with all the contributions, so I decided to refactor it. In the meantime, it turned out that the vscode API module had gone through major changes, so I migrated the extension as well. As a result, there are give or take three different issues which are addressed by the prospective PR, but they depend on each other. If one of them is rejected, I will probably have to rewrite the other two. Hence the question: at first glance, which parts do you think you would be interested in?

The refactoring was done by turning the code into classes and separating hard-coded constants from the actual processing, which was further broken into smaller pieces. On one hand, this is generally more contribution-friendly, as you can clearly see which function does what and modify it while not touching the rest. On the other hand, this does introduces some layer of complexity and I am not sure if this is something you want in your project. Another thing I am not sure of is code formatting – I have used something close to PSR-2, but chances are that Prettier would be better. However, this is something we can discuss directly in the PR.

Here is the fork: https://github.com/butteredptarmigan/vscode-shell-command

Looking forward for your feedback 🐈

**Comment by augustocdias** [comment]
Hey, thank you very much. 
I’m no expert in typescript or JavaScript and I just wanted the job done when I started this extension and I had no expectation that it would draw any attention from the community. 
So I acknowledge and agree that it’s not the best code I’ve ever written. 

I’d feel happy to accept any contribution to make it better or add more features. 
If you prefer you can just make a big pull request with everything as well. 
I don’t mind reviewing it :)
Thank you again.

**Comment by augustocdias** [comment]
I have just published
Thanks :)
