### ISSUE TITLE
The fieldSeparator functionality no longer works in version 1.8.0

### ISSUE THREAD

**Issue by rvogg** [augustocdias/vscode-shell-command#61]
After updating to version 1.8.0, the fieldSeparator functionality no longer works. 

Here is an example with version 1.7.5:
![version-1 7 5](https://user-images.githubusercontent.com/6071852/221442474-c49bfc86-31cc-451f-8863-309c73b8f19b.png)

and here the same example with version 1.8.0:
![version-1 8 0](https://user-images.githubusercontent.com/6071852/221442486-d759fde2-314a-42e1-a21d-e44dbd69a541.png)

In the selection list only the label is visible and instead of the value field the label is used for variable substitution.

**Comment by augustocdias** [comment]
@quentingllmt could you help taking a look on this?

**Comment by augustocdias** [comment]
I've found the reason for this one and just pushed a fix. Will publish as soon as I find the reason for the other open issue
