### ISSUE TITLE
broken multi root workspace support for input variables

### ISSUE THREAD

**Issue by simonste** [augustocdias/vscode-shell-command#63]
https://github.com/augustocdias/vscode-shell-command/pull/50 dropped the support for multi folder workspaces

Test example:
[example.zip](https://github.com/augustocdias/vscode-shell-command/files/10861364/example.zip)

**Comment by ahfakt** [comment]
I can't see any task in folders. What is the problem with comparing before and after.

**Comment by simonste** [comment]
I created a PR: https://github.com/augustocdias/vscode-shell-command/pull/64

This seems to fix the issue.
@ahfakt: did you intentionally leave the launchInputs.globalValue out?

**Comment by ahfakt** [comment]
@simonste: No, I have never used launch.json so wasn't aware that case.
