### ISSUE TITLE
Avoid selection if only one option was given via commandline

### ISSUE THREAD

**Issue by ephraim** [augustocdias/vscode-shell-command#78]
Is it possible to avoid the selection process , when only one option (one line) was given by the  commandline process.

It would by really nice, if this would be configurable via a boolean variable.

Thanks!

Cheers,
Thilo

**Comment by ephraim** [comment]
I think this is vscode related not, shellCommand.execute related.
Sorry for the noise!

**Comment by augustocdias** [comment]
Check the `useFirstResult` and `useSingleResult` options in the docs
