### ISSUE TITLE
Issue #79 has come back in 1.9.2

### ISSUE THREAD

**Issue by tmaslach** [augustocdias/vscode-shell-command#84]
Hi!  https://github.com/augustocdias/vscode-shell-command/issues/79 seems to have cropped back up.  I wasn't sure if I should create a new issue or just comment on the old one.  I've decided to open up a new issue.  

Let me know if you have any questions!  #79 has details on how to reproduce.

**Comment by MarcelRobitaille** [comment]
Hi. Thank you for reporting. I'm really sorry about that. We really need some automated tests...

I will have a look in the next days. In the mean time, does 1.9.1 work for you?

**Comment by tmaslach** [comment]
Yep, that should work - thanks!

**Comment by MarcelRobitaille** [comment]
Should be fixed in e144f3e28c8ca10c394a712067289d7af6785005
