### ISSUE TITLE
Add possibility to read output from stderr

### ISSUE THREAD

**Issue by AJIOB** [augustocdias/vscode-shell-command#86]
# Current behavior

Plugin reads from the stdout only

# Suggested behavior

We can select to read from stdout, stderr or from both of them

# Why need

By default, CMake prints `NOTICE` messages to the stderr (the messages without dashes). More info [here](https://cmake.org/cmake/help/latest/command/message.html#general-messages).

**Comment by augustocdias** [comment]
This should be doable. We'd need to use the `spawnSync` function instead of `execSync` 

https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options

**Comment by MarcelRobitaille** [comment]
Wouldn't it be possible to do all of this with redirects? `"command": "cmake blah blah 2>&1"` You can also select only the stderr `"command": "cmake blah blah 2>&1 1>/dev/null"`

**Comment by AJIOB** [comment]
> Wouldn't it be possible to do all of this with redirects? `"command": "cmake blah blah 2>&1"` You can also select only the stderr `"command": "cmake blah blah 2>&1 1>/dev/null"`

It's ok if it possible to do on Windows & Linux together, not by creating two different tasks
